#!/bin/sh
clip=$(xsel -bo | sed 's|https://||g' | \
sed 's|www.||g')

grep "^${clip}\$" ~/.local/share/bookmarks/bookmarks || \
    (echo $clip >> \
    ~/.local/share/bookmarks/bookmarks && \
    echo "" >> ~/.local/share/bookmarks/bookmarks)
