#!/bin/sh
# fzf script for picking locally downloaded anime

FSEL="$(find ~/Videos/not-anime/ -type f| \
    awk -F'/' '{ print $NF }' | fzf --no-info)"

if [ -z "$FSEL" ]
then
    exit
fi

devour mpv "$(find ~/Videos/not-anime -type f | fgrep "$FSEL")"

