#!/bin/sh

# sets keyboard repeat rate
xset r rate 250 40

# wallpaper
hsetroot -cover ~/Pictures/wallpapers/wp.jpg

# numlock activate
exec numlockx &

# compositor
exec picom &

# audio server
exec /usr/bin/pipewire &
exec /usr/bin/pipewire-pulse &
exec /usr/bin/wireplumber &

# keyboard shortcuts
exec sxhkd -c ~/.config/sxhkd/sxhkdrc &

exec mpd &
exec mpDris2 &

brightnessctl s 11%

# input thingy
exec touchsets &
exec unclutter --timeout 3 &

exec dwmblocks &

# Telemetry
#exec aw-server &
#exec aw-watcher-window &
#exec aw-watcher-afk &

# Start dunstd
notify-send -t 1 "w"
