#!/bin/sh

# sets keyboard repeat rate
xset r rate 250 40

# kill from previous session
pkill pipewire-pulse
pkill pipewire
pkill wireplumber

pkill sxhkd
pkill dwmblocks

killall mpd
pkill mpDris2
pkill mpdup

# wallpaper
#hsetroot -cover ~/Pictures/wallpapers/wp.jpg

# numlock activate
exec numlockx &

# compositor
exec picom --experimental-backends &

# audio server
exec /usr/bin/pipewire &
exec /usr/bin/pipewire-pulse &
exec /usr/bin/wireplumber &

# keyboard shortcuts
pkill sxhkd
exec sxhkd -c ~/.config/sxhkd/sxhkdrc &

#exec mpd &
#exec mpDris2 &

brightnessctl s 11%

# input thingy
exec otd &
exec touchsets &
exec unclutter --timeout 3 &

exec dwmblocks &
