#!/bin/sh
# start from startx or sx

# sets keyboard repeat rate
xset r rate 250 40

# kill from previous session
pkill pipewire-pulse
pkill pipewire
pkill wireplumber

pkill sxhkd
pkill dwmblocks
pkill mpdup

killall mpd
pkill mpDris2

# wallpaper
hsetroot -fill ~/Pictures/wallpapers/yuyuko.jpg

# numlock activate
exec numlockx &

# compositor
exec picom --experimental-backends &

# audio server
exec /usr/bin/pipewire &
exec /usr/bin/pipewire-pulse &
exec /usr/bin/wireplumber &

# keyboard shortcuts
pkill sxhkd
exec sxhkd -c ~/.config/sxhkd/sxhkdrc &

# mpd
mpd &
mpDris2 &
exec mpdup &

# set brightness
brightnessctl s 11%

# input thingy
exec touchsets &
exec unclutter --timeout 3 &

# bar
exec dwmblocks &
