#!/bin/sh
file=$(du ~/.config -aLd 4 -S --exclude='obs-studio'\
    --exclude='lutris' --exclude='pulse'\
    --exclude='BraveSoftware' --exclude='.git'\
    --exclude='*runtime' --exclude='*.o'\
    --exclude='nuclear' --exclude='*.png'\
    --exclude='*.jpg' --exclude='\.git*'\
    --exclude='VSCodium' --exclude='VirtualBox'\
    --exclude='.lock' --exclude='Signal'\
    --exclude='GIMP' --exclude='discord'\
    --exclude='Element' --exclude='libreoffice'\
    --exclude='libvirt' --exclude='qt5ct'\
    --exclude='coc' --exclude='cef_user_data'\
    --exclude='spotdl' --exclude='recidia'\
    --exclude='OpenTabletDriver' --exclude='inkscape'\
    --exclude='lapce' --exclude='ttyper'\
    --exclude='*.log' --exclude='qBittorrent'\
    --exclude='watch_later' --exclude='*.db'\
    --exclude='mypaint' --exclude='termusic'\
    --exclude='qutebrowser' --exclude='lapce-stable'\
    --exclude='unity' --exclude='ibus'\
    --exclude='gtk-3.0' --exclude='Google'\
    --exclude='fcitx'\
    2>/dev/null | awk '{ print $2}' | fzf --no-info)

if [ $? -eq 130 ]; then
    exit 130
fi

nvim $file
