#!/bin/sh
FSEL="$(find ~/Videos/not-anime/ -type f| \
    awk -F'/' '{ print $NF }' | dmenu -l 20\
    -sb "#a62ca6" -i -p "Anime" -fn \
    "JetBrains Mono:size=10:style=Bold:antialias=true:autohint=true")"

if [ -z "$FSEL" ]
then
    exit
fi

mpv "$(find ~/Videos/not-anime -type f | fgrep "$FSEL")"

