#!/bin/sh
DSEL="$(find ~/Videos/not-anime/ -type d | \
    awk -F'/' '{ print $NF }' | dmenu -l 20\
    -sb "#a62ca6" -i -p "Select anime " -fn \
    "JetBrains Mono:size=10:style=Bold:antialias=true:autohint=true")"

if [ -z "$DSEL" ]
then
    exit
fi

echo $DSEL

FSEL="$(find ~/Videos/not-anime/ -type f | \
    fgrep "$DSEL" | awk -F'/' '{ print $NF }' | \
    awk -F'/' '{ print $NF }' | dmenu -l 20 \
    -sb "#a62ca6" -i -p "Select episode " -fn \
    "JetBrains Mono:size=10:style=Bold:antialias=true:autohint=true")"

if [ -z "$FSEL" ]
then
    exit
fi

mpv "$(find ~/Videos/not-anime -type f | fgrep "$FSEL")"
