#!/bin/bash
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    case "$1" in
        on) hyprsunset -t 5100 &>/dev/null &!
            ;;
        off) killall hyprsunset
            ;;
        *) hyprsunset -t 5100 &>/dev/null &!
            ;;
    esac
else
    case "$1" in
        on) redshift -P -O 5000 &>/dev/null
            ;;
        off) redshift -x &>/dev/null
            ;;
        *) redshift -P -O 5000 &>/dev/null
            ;;
    esac
fi

