#!/bin/sh
if [ -z "$1" ]
then
  prompt () {
  	# prompts the user with message in $1-2 ($1 in blue, $2 in magenta) and saves the input to the variables in $REPLY and $REPLY2
  	printf "\033[1;34m%s\033[1;35m%s\033[1;34m: \033[0m" "$1" "$2"
  	read -r REPLY
    read -r REPLY2
  }
  prompt "enter file directory"
  FD="$REPLY"
  FDO="$REPLY2"
else
  FD="$1"
  FDO="$2"
fi

#comp="\$comp"

echo "rsync -urvP $FD \"\$comp\":$FDO" >> $HOME/.local/bin/prsync

