#!/bin/sh
if [ "$XDG_SESSION_TYPE" == 'wayland' ]; then
    USEL=$(tofi --prompt-text="Remove bookmark: " \
        < ~/.local/share/bookmarks/bookmarks)
else
    USEL=$(dmenu -l 20 -sb "#a62ca6" -nb "#000001" -p "Remove bookmark " -fn \
    "JetBrains Mono:size=10:style=Bold:antialias=true:autohint=true" \
    < ~/.local/share/bookmarks/bookmarks)
fi
if [ -z "$USEL" ]
then
    exit
fi

GEL=$(grep -v $USEL ~/.local/share/bookmarks/bookmarks)

echo $GEL | sed 's/ /\n/g' > ~/.local/share/bookmarks/bookmarks
