#!/bin/bash
file_name=$(date +%Y-%m-%d_%H-%M-%S).png
file_path="$HOME/Pictures/Screenshots/unnamed/$file_name"

output=$(maim -u -s $file_path)

if [ $? -eq 0 ]; then
	display=$(echo Saved to $file_path)
	notify-send "Screenshot" "$display"
else
	err=$(echo Something went wrong... "$output")
	notify-send "Screenshot" "$err"
fi
