#!/bin/sh

set -e

default_filename="$(date +%Y-%m-%d_%H-%M-%S).png"
default_filepath="$HOME/Pictures/Screenshots/unnamed"
history="$XDG_CACHE_HOME/screenshot-save-paths"

filepath=""
filename=""

[ -e "$history" ] || echo "$HOME\n$default_filepath" > "$history"

if [ "$XDG_SESSION_TYPE" = 'wayland' ]; then
    if [ "$1" = 'w' ]; then
        grim "/tmp/$default_filename"
    else
        grim -g "$(slurp)" "/tmp/$default_filename"
    fi

    filepath=`tac "${history}" | tofi`
    if [ -z "$filepath" ]; then
        rm "/tmp/$default_filename"
        exit 1
    fi
    filepath=`realpath "${filepath}"`

    random_filename="$(head -c 13 /proc/sys/kernel/random/uuid).png"
    simple_date_filename="$(date +%Y-%m-%d).png"
    filename=`echo "$default_filename\n$random_filename\n$simple_date_filename" | tofi`
    if [ -z "$filename" ]; then
        exit 1
    fi

    mv "/tmp/$default_filename" "${filepath}/${filename}"

    sed -i 's:^'"${filepath}"'$::g' "$history"
    sed -i '/^$/d' "$history"
    echo "${filepath}" >> "$history"
fi

if [ $? -eq 0 ]; then
	notify-send "Screenshot" "Saved to ${filepath}/${filename}"
else
	err=$(echo Something went wrong...)
	notify-send "Screenshot" "$err"
fi
