#!/bin/bash

if [ "$XDG_SESSION_TYPE" = 'wayland' ]; then
    hyprshot -m window --clipboard-only
else
    maim -u -s | xclip -selection clipboard -t image/png
fi

if [ $? -eq 0 ]; then
    notify-send "Screenshot" "Saved to clipboard"
else
    notify-send "Screenshot" "Something went wrong..."
fi
