#!/bin/sh

set -e

susdir=$HOME/Documents/org/
sustar="${susdir}/sus.tar"
susencrypt="${susdir}/sus.tar.gpg"
sussy_file=$(date +%Y-%m-%d).txt
recipient=34E8F9595132FE4897B3CF88FA2A15E74BB05411

rng=$(shuf -i 1-10 -n 1)

#
if [ $rng -eq 1 ]; then
	susback="${susencrypt}-$(date +%Y-%m-%d_%H-%M)"
	cp "$susencrypt" "$susback"
	echo "Backing up to ${susback}..."
fi

gpg -d "$susencrypt" > "$sustar"
tar xf "$sustar" -C "$susdir"

$EDITOR "${susdir}/sus/${sussy_file}"
tar cf "${susdir}/sus.tar" --directory="${susdir}" ./sus
rm -rf "${sustar}.gpg"
gpg -e --recipient "$recipient" "$sustar"
rm -rf "$sustar"
rm -rf "${susdir}/sus" || (echo "SOMETHING FAILED" && \
echo tar with \
tar cf "${susdir}/sus.tar" --directory="${susdir}" ./sus && \
echo re-encrypt with \
gpg -e --recipient "$recipient" "$sustar")
