#!/bin/sh

tnum=$(xinput | grep Touchpad | awk -F "=" '{ print $2 }' | awk -F " " '{ print $1 }')

## acceleration
xinput --set-prop $tnum 'libinput Accel Profile Enabled' 0, 1

## cursor speed
xinput --set-prop $tnum 'libinput Accel Speed' 0.4

## tap
xinput --set-prop $tnum 'libinput Tapping Enabled' 1


