#!/bin/sh
if [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 86 ]; then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
elif [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 68 ]; then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
elif [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 39 ]; then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
elif [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 13 ]; then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
elif [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 1 ]; then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
fi
