#!/bin/sh
if [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 92 ]
then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
elif [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 76 ]
then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
elif [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 40 ]
then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
elif [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 14 ]
then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
elif [ $(acpi | awk -F, '{ print $2 }' | sed 's/%//g') -gt 1 ]
then
	echo " ^c#81A1C1^^b#2e2e2e^  $(acpi | awk -F, '{ print $2 }')"
fi
