#!/bin/sh
echo "^c#c441d4^  TODO ^c#bd93f9^ $(sed -n '6,6p' "/home/bruh/vimwiki/todo.wiki" | awk -F'] ' {' print $2'}) ^d^"
#echo "^c#2E3440^^b#d6acff^  TODO ^c#44475a^^b#bd93f9^ $(sed -n '6,6p' "/home/bruh/vimwiki/todo.wiki" | awk -F'] ' {' print $2'}) ^d^"
